dotnet/src/overnight.WWW/Areas/Backoffice/Controllers/OrganisationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using overnight.Db;
using overnight.Models;
using overnight.Models.Security;
using overnight.Models.Utilities;
using overnight.Models.ViewModels;

namespace overnight.WWW.Areas.Backoffice.Controllers 
{
    [Area("Backoffice")]
    public class OrganisationController : BaseController 
    {
        public OrganisationController(ApplicationDbContext applicationDbContext):base(applicationDbContext)
        {
        }

        public async Task<IActionResult> Index() 
        {
            var model = await ApplicationDbContext.Organisations.OrderBy(o => o.Name).ToListAsync();

            if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest") 
            {
                return PartialView("_ListPartial", model);
            }
            
            return View(model);

        }

        [HttpGet]
        public IActionResult Create() 
        {
            var model = new Organisation();

            return View(model);
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Organisation model)
        {
            var alert = new Alert();
            try
            {
                if(!ModelState.IsValid) {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }
                    
                
                ApplicationDbContext.Organisations.Add(model);
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.CREATENOK;
                    throw new Exception();
                }   

                alert.Message = ApplicationDbContextMessage.CREATEOK;
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;
                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Int16? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            
            var model = await ApplicationDbContext.Organisations.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Organisation model)
        {
            var alert = new Alert();
            try 
            {
                if(!ModelState.IsValid)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }   
                    
                var originalModel = ApplicationDbContext.Organisations.FirstOrDefault(m => m.Id == model.Id);
                
                if(originalModel == null) 
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }
                    
                originalModel.Name = model.Name;
                originalModel.Description = model.Description;
                
                ApplicationDbContext.Organisations.Attach(originalModel);
                ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.EDITNOK;
                    throw new Exception();
                } 
                
                alert.Message = ApplicationDbContextMessage.EDITOK;
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }

        [HttpGet("[area]/[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Delete(Int16 id, [FromQuery] ActionType actionType)
        {
            var model = await ApplicationDbContext.Organisations.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            //model specifiek voor een view + bijkomende informatie
            //lijst van categorien waar uit kan gekozen worden
            var viewModel = new ActionOrganisationViewModel()
            {
                BaseEntity = model,
                ActionType = actionType
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ActionOrganisationViewModel model)
        {
            var alert = new Alert();// Alert
            try
            {
                var originalModel = ApplicationDbContext.Organisations.FirstOrDefault(m => m.Id == model.BaseEntity.Id);
                
                if(originalModel == null)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }

                switch(model.ActionType)
                {
                    case ActionType.Delete:
                        alert.Message = ApplicationDbContextMessage.DELETEOK;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Deleted;
                        break;
                    case ActionType.SoftDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTDELETEOK;
                        originalModel.DeletedAt = DateTime.Now;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                    case ActionType.SoftUnDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTUNDELETEOK;
                        originalModel.DeletedAt = (Nullable<DateTime>)null;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                }

                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {                   
                    switch(model.ActionType)
                    {
                        case ActionType.Delete:
                            alert.Message = ApplicationDbContextMessage.DELETENOK;
                            break;
                        case ActionType.SoftDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTDELETENOK;
                            break;
                        case ActionType.SoftUnDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTUNDELETENOK;
                            break;
                    }
                    throw new Exception();
                } 

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

dotnet/src/overnight.WWW/Areas/Backoffice/Views/Organisation/Create.cshtml
@model overnight.Models.Organisation
@{
    ViewBag.Title = "Organisation Management";
    ViewBag.SubTitle = "Manage all your groups via this platform";
    ViewBag.Description = "Create an organisation via the form or got back to the list of organisations ...";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.Partial("_QuickActionsPartial")
</div>



 <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3><i class="fa fa-plus fa-fw"></i> Add New</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-6">


                                        <form role="form" asp-controller="Organisation" asp-action="Create" method="post" asp-antiforgery="true">                                       
                                            <div class="form-group">
                                                <label asp-for="Name">Name</label>
                                                <input class="form-control" placeholder="Enter name" asp-for="Name">
                                            </div>  

                                            <div class="form-group">
                                                <label asp-for="Description">Description</label>
                                                <input class="form-control" placeholder="Enter the description" asp-for="Description">
                                            </div>   

                                            <button type="submit" class="btn btn-default">Save</button>
                                        </form>


                                    </div>
                                    
                                </div>
                                <!-- /.row (nested) -->
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->

dotnet/src/overnight.WWW/Areas/Backoffice/Views/Organisation/Delete.cshtml
@model overnight.Models.ViewModels.ActionOrganisationViewModel
@{
    ViewBag.Title = "Organisation Management";
    ViewBag.SubTitle = "Manage all the organisations on your SAAS platform";
    ViewBag.Description = "Create an organisation via the form or go back to the list of organisations.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.Partial("_QuickActionsPartial")
</div>

 <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3><i class="fa fa-edit fa-fw"></i> Edit</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-6">


                 <p>Do you wish to @Model.Action the organisation <b> @Model.BaseEntity.Name</b>?</p>
                <form asp-controller="Organisation" asp-action="Delete" method="post" asp-antiforgery="true">
                <input asp-for="BaseEntity.Id" type="hidden">
                <input asp-for="BaseEntity.Name" type="hidden">
                <input asp-for="BaseEntity.Description" type="hidden">
                <input asp-for="ActionType" type="hidden">
                <button type="submit" class="btn btn-default">@Model.Action</button>
            </form>

                                           
                                     

                                    </div>
                                    
                                </div>
                                <!-- /.row (nested) -->
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->

dotnet/src/overnight.WWW/Areas/Backoffice/Views/Organisation/Edit.cshtml
@model overnight.Models.Organisation
@{
    ViewBag.Title = "Organisation Management";
    ViewBag.SubTitle = "Manage all the organisations on your SAAS platform";
    ViewBag.Description = "Edit an existing organisation via the form or go back to the list of organisations.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.Partial("_QuickActionsPartial")
</div>

 <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3><i class="fa fa-edit fa-fw"></i> Edit</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-6">


                                        <form role="form" asp-controller="Organisation" asp-action="Edit" method="post" asp-antiforgery="true">                                       
                                            <div class="form-group">
                                                <label asp-for="Name">Name</label>
                                                <input class="form-control" placeholder="Enter name" asp-for="Name">
                                            </div>  

                                            <div class="form-group">
                                                <label asp-for="Description">Description</label>
                                                <input class="form-control" placeholder="Enter the description" asp-for="Description">
                                            </div>   

                                            <button type="submit" class="btn btn-default">Update</button>
                                        </form>


                                    </div>
                                    
                                </div>
                                <!-- /.row (nested) -->
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->

dotnet/src/overnight.WWW/Areas/Backoffice/Views/Organisation/Index.cshtml
@model ICollection<overnight.Models.Organisation>
@{
    ViewBag.Title = "Overnachtingen";
    ViewBag.SubTitle = "Beheer alle overnachtingen via dit platform";
    ViewBag.Description = "Selecteer een overnachting om te bewerken";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.Partial("_QuickActionsPartial")

    <div class="row">
                        <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                               <h3><i class="fa fa-desktop fa-fw"></i> Overview</h3>
                            </div>
                            <div class="panel-body">
                                @Html.Partial("_ListPartial", @Model)
                                
                            </div>
                        
                        </div>
                    </div>
                    </div>

         
</div>





                  

dotnet/src/overnight.WWW/Areas/Backoffice/Views/Organisation/_ListPartial.cshtml
@model ICollection<overnight.Models.Organisation>
@Html.AntiForgeryToken()
@if (Model != null && Model.Count() > 0)
{
     <!-- <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable is-upgraded ahs-table" data-upgraded=",MaterialDataTable">
        <colgroup>
          <col class="auto-cell-size p-r-20">
        </colgroup>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Created</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          @foreach (var organisation in Model)
          {
            <tr data-id="organisation-@organisation.Id">
              <td>@organisation.Name</td>
              <td>@organisation.Description</td>
              <td>@organisation.CreatedAt</td>
              <td>
                <a asp-controller="Organisation" asp-action="Edit" asp-route-id="@organisation.Id">
                  <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">edit</i>
                </a>
                @if (@organisation.DeletedAt != null)
                {
                    <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="5" data-is-softdelete="true">
                      <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>
                    </a>
                }
                else
                {
                    <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="4">
                      <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>
                    </a>
                }
                <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="3">
                  <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete_forever</i>
                </a>
              </td>
            </tr>
          }
        </tbody>
      </table>-->

       <table class="table table-hover" data-upgraded=",MaterialDataTable">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Description</th>
                                                <th>Created</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                         <tbody>
          @foreach (var organisation in Model)
          {
            <tr data-id="organisation-@organisation.Id">
              <td>@organisation.Name</td>
              <td>@organisation.Description</td>
              <td>@organisation.CreatedAt</td>
              <td>
                <a asp-controller="Organisation" asp-action="Edit" asp-route-id="@organisation.Id">
                  <i class="fa fa-edit fa-fw"></i>
                </a>
                @if (@organisation.DeletedAt != null)
                {
                    <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="5" data-is-softdelete="true">
                      <i class="fa fa-trash fa-fw"></i>
                    </a>
                }
                else
                {
                    <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="4">
                      <i class="fa fa-trash fa-fw"></i>
                    </a>
                }
                <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="3">
                  <i class="fa fa-eraser fa-fw"></i>
                </a>
              </td>
            </tr>
          }
        </tbody>
</table>
}
else
{
    <p>No Organisations in the database!</p>
}
</div>

dotnet/src/overnight.WWW/Areas/Backoffice/Views/Organisation/_QuickActionsPartial.cshtml
<!--<div class="ahs-list-overview">
    <div class=" mdl-color-text--blue-grey-400">
        <h3><i class=" material-icons f-left m-r-5">dvr</i> Overview</h3>
        <p>@ViewBag.Description</p>
        <ul class="ahs-list-overview__list">
            <li><a asp-controller="Organisation" asp-action="Index"><i class="material-icons">list</i>List of items</a></li>
            <li><a asp-controller="Organisation" asp-action="Create"><i class="material-icons">add</i>Create a new item</a></li>
            <li><a href=""><i class="material-icons">file_download</i>Export items</a></li>
        </ul>
    </div>
</div>-->


                    <div class="row">
            
                            <div class="panel-body">
                                <p>@ViewBag.Description</p>

                                <ul class="ahs-list-overview__list">
                                    <li><a asp-controller="Organisation" asp-action="Index"><i class="fa fa-list fa-fw"></i>List of items</a></li>
                                    <li><a asp-controller="Organisation" asp-action="Create"><i class="fa fa-plus fa-fw"></i>Create a new item</a></li>
                                    <li><a href=""><i class="fa fa-upload fa-fw"></i>Export items</a></li>
                             </ul>
                                
                           
                    </div>
                    </div>
               